tasks:
  execute-tests:
    type: build
    runner:
      os_image: ubuntu
      containers:
      - image: redis # cache service
      - image: postgres # db service
        environment:
        - POSTGRES_DB=test
    steps:
    - commands:
      # Wait for the containers to be healthly using dockerize CLI
      # dockerize: https://github.com/jwilder/dockerize
      - dockerize -wait tcp://localhost:5432 -wait tcp://localhost:6379
