global:
  runner:
    tasks:
      Compile:
        steps:
        - run: echo "Compiled Successfully"

      JUnit:
        steps:
        - run: echo "JUnit passed Succesfully"

      Quality-Gate:
        steps:
        - run: echo "Quality Gate passed Successfully"

      Deploy:
        steps:
        - run: echo "Pass"

  
